import dotenv from 'dotenv';
dotenv.config();

import connectDB from './config/database';
import Product from './models/Product';
import mongoose from 'mongoose';

const products = [
  {
    name: 'Wireless Bluetooth Headphones',
    description: 'Premium noise-cancelling wireless headphones with 30-hour battery life',
    price: 79.99,
    image: 'https://images.pexels.com/photos/3587478/pexels-photo-3587478.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 15,
    rating: 4.5,
    numReviews: 120,
  },
  {
    name: 'Wireless Mouse',
    description: 'Ergonomic wireless mouse with precision tracking',
    price: 29.99,
    image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 30,
    rating: 4.2,
    numReviews: 85,
  },
  {
    name: 'USB-C Charging Cable',
    description: 'Durable USB-C charging cable with fast charging support',
    price: 12.99,
    image: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 50,
    rating: 4.0,
    numReviews: 45,
  },
  {
    name: 'Laptop Stand',
    description: 'Adjustable aluminum laptop stand for ergonomic workspace',
    price: 39.99,
    image: 'https://images.pexels.com/photos/7214/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 20,
    rating: 4.6,
    numReviews: 95,
  },
  {
    name: '4K Webcam',
    description: 'Crystal clear 4K resolution webcam for streaming and calls',
    price: 89.99,
    image: 'https://images.pexels.com/photos/4290320/pexels-photo-4290320.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 12,
    rating: 4.4,
    numReviews: 78,
  },
  {
    name: 'Mechanical Keyboard',
    description: 'RGB mechanical keyboard with customizable switches',
    price: 129.99,
    image: 'https://images.pexels.com/photos/7923/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 18,
    rating: 4.7,
    numReviews: 156,
  },
  {
    name: 'Portable SSD 1TB',
    description: 'Fast portable solid state drive with 1TB storage',
    price: 119.99,
    image: 'https://images.pexels.com/photos/4195325/pexels-photo-4195325.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 25,
    rating: 4.6,
    numReviews: 203,
  },
  {
    name: 'USB Hub with 7 Ports',
    description: 'Multi-port USB hub for connecting multiple devices',
    price: 34.99,
    image: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 40,
    rating: 4.3,
    numReviews: 67,
  },
  {
    name: 'Wireless Charging Pad',
    description: 'Fast wireless charging pad for compatible devices',
    price: 24.99,
    image: 'https://images.pexels.com/photos/3587478/pexels-photo-3587478.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 35,
    rating: 4.2,
    numReviews: 92,
  },
  {
    name: 'LED Desk Lamp',
    description: 'Energy-efficient LED desk lamp with adjustable brightness',
    price: 44.99,
    image: 'https://images.pexels.com/photos/1038169/pexels-photo-1038169.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 22,
    rating: 4.5,
    numReviews: 134,
  },
  {
    name: 'Bluetooth Speaker',
    description: 'Portable Bluetooth speaker with powerful bass',
    price: 59.99,
    image: 'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 28,
    rating: 4.4,
    numReviews: 110,
  },
  {
    name: 'Monitor Stand',
    description: 'Sturdy monitor stand with storage compartment',
    price: 49.99,
    image: 'https://images.pexels.com/photos/7214/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 16,
    rating: 4.3,
    numReviews: 74,
  },
  {
    name: 'Wireless Mouse Pad',
    description: 'Large wireless charging mouse pad',
    price: 54.99,
    image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 24,
    rating: 4.6,
    numReviews: 88,
  },
  {
    name: 'Cooling Laptop Pad',
    description: 'Laptop cooling pad with USB power',
    price: 34.99,
    image: 'https://images.pexels.com/photos/7214/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 19,
    rating: 4.4,
    numReviews: 63,
  },
  {
    name: 'HDMI Cable 10ft',
    description: '4K HDMI cable with gold-plated connectors',
    price: 14.99,
    image: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 60,
    rating: 4.2,
    numReviews: 51,
  },
  {
    name: 'USB 3.0 Cable',
    description: 'Fast USB 3.0 data transfer cable',
    price: 9.99,
    image: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 80,
    rating: 4.1,
    numReviews: 44,
  },
  {
    name: 'Power Bank 20000mAh',
    description: 'High capacity power bank with dual USB ports',
    price: 39.99,
    image: 'https://images.pexels.com/photos/4195325/pexels-photo-4195325.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 32,
    rating: 4.5,
    numReviews: 167,
  },
  {
    name: 'Screen Protector Pack',
    description: '5-pack tempered glass screen protectors',
    price: 19.99,
    image: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 45,
    rating: 4.3,
    numReviews: 82,
  },
  {
    name: 'Phone Stand',
    description: 'Adjustable universal phone stand',
    price: 14.99,
    image: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 38,
    rating: 4.4,
    numReviews: 71,
  },
  {
    name: 'Cable Organizer',
    description: 'Cable management clips and organizers set',
    price: 11.99,
    image: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 50,
    rating: 4.2,
    numReviews: 48,
  },
  {
    name: 'Laptop Backpack',
    description: 'Water-resistant laptop backpack with USB port',
    price: 59.99,
    image: 'https://images.pexels.com/photos/1334597/pexels-photo-1334597.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 17,
    rating: 4.6,
    numReviews: 124,
  },
  {
    name: 'Mouse Pad XL',
    description: 'Large extended mouse pad for gaming',
    price: 24.99,
    image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 29,
    rating: 4.3,
    numReviews: 69,
  },
  {
    name: 'Portable Charger',
    description: 'Compact portable charger with fast charging',
    price: 29.99,
    image: 'https://images.pexels.com/photos/4195325/pexels-photo-4195325.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 41,
    rating: 4.4,
    numReviews: 103,
  },
  {
    name: 'USB-A Hub',
    description: 'Compact USB-A hub with 4 ports',
    price: 19.99,
    image: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 33,
    rating: 4.2,
    numReviews: 57,
  },
  {
    name: 'Desk Organizer',
    description: 'Multi-compartment desk organizer',
    price: 29.99,
    image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 26,
    rating: 4.3,
    numReviews: 76,
  },
  {
    name: 'Phone Case Protective',
    description: 'Durable protective phone case',
    price: 16.99,
    image: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 55,
    rating: 4.4,
    numReviews: 137,
  },
  {
    name: 'Anti-Glare Screen',
    description: 'Anti-glare screen protector for monitors',
    price: 34.99,
    image: 'https://images.pexels.com/photos/7214/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 20,
    rating: 4.2,
    numReviews: 53,
  },
  {
    name: 'Keyboard Cover',
    description: 'Transparent keyboard cover dust protector',
    price: 12.99,
    image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 42,
    rating: 4.1,
    numReviews: 61,
  },
  {
    name: 'Monitor Light Bar',
    description: 'Smart monitor light bar for better lighting',
    price: 99.99,
    image: 'https://images.pexels.com/photos/1038169/pexels-photo-1038169.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 11,
    rating: 4.7,
    numReviews: 142,
  },
  {
    name: 'Desk Lamp with USB',
    description: 'LED desk lamp with USB charging port',
    price: 34.99,
    image: 'https://images.pexels.com/photos/1038169/pexels-photo-1038169.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 23,
    rating: 4.5,
    numReviews: 86,
  },
  {
    name: 'Wireless Earbuds Pro',
    description: 'Premium wireless earbuds with active noise cancellation',
    price: 159.99,
    image: 'https://images.pexels.com/photos/3587478/pexels-photo-3587478.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 14,
    rating: 4.8,
    numReviews: 198,
  },
  {
    name: 'USB-C Hub Pro',
    description: 'Professional USB-C hub with multiple ports',
    price: 79.99,
    image: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 13,
    rating: 4.6,
    numReviews: 114,
  },
  {
    name: 'Laptop Sleeve',
    description: 'Neoprene laptop sleeve with padding',
    price: 24.99,
    image: 'https://images.pexels.com/photos/1334597/pexels-photo-1334597.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 31,
    rating: 4.3,
    numReviews: 79,
  },
  {
    name: 'Gaming Mouse Pad',
    description: 'RGB gaming mouse pad with hard surface',
    price: 44.99,
    image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 27,
    rating: 4.5,
    numReviews: 96,
  },
  {
    name: 'Monitor Arm Mount',
    description: 'Adjustable monitor arm desk mount',
    price: 69.99,
    image: 'https://images.pexels.com/photos/7214/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 9,
    rating: 4.7,
    numReviews: 151,
  },
  {
    name: 'Webcam Ring Light',
    description: 'Ring light for webcam with adjustable brightness',
    price: 44.99,
    image: 'https://images.pexels.com/photos/1038169/pexels-photo-1038169.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 19,
    rating: 4.4,
    numReviews: 73,
  },
  {
    name: 'Desk Cable Box',
    description: 'Plastic cable management box',
    price: 19.99,
    image: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 37,
    rating: 4.2,
    numReviews: 58,
  },
  {
    name: 'Laptop Dock',
    description: 'Universal laptop docking station',
    price: 94.99,
    image: 'https://images.pexels.com/photos/7214/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 8,
    rating: 4.6,
    numReviews: 127,
  },
  {
    name: 'Ergonomic Keyboard',
    description: 'Split ergonomic keyboard for comfort',
    price: 89.99,
    image: 'https://images.pexels.com/photos/7923/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 16,
    rating: 4.5,
    numReviews: 99,
  },
  {
    name: 'USB Splitter Cable',
    description: 'USB splitter for dual device charging',
    price: 9.99,
    image: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 72,
    rating: 4.0,
    numReviews: 39,
  },
  {
    name: 'Monitor Riser',
    description: 'Adjustable monitor riser with storage',
    price: 39.99,
    image: 'https://images.pexels.com/photos/7214/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 21,
    rating: 4.4,
    numReviews: 81,
  },
  {
    name: 'Cable Ties Pack',
    description: 'Reusable cable ties pack of 20',
    price: 8.99,
    image: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 85,
    rating: 4.1,
    numReviews: 46,
  },
  {
    name: 'Phone Holder Stand',
    description: 'Portable phone holder stand for desk',
    price: 12.99,
    image: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 48,
    rating: 4.3,
    numReviews: 68,
  },
  {
    name: 'Desk Lamp Clip',
    description: 'Clip-on desk lamp for monitor',
    price: 29.99,
    image: 'https://images.pexels.com/photos/1038169/pexels-photo-1038169.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 25,
    rating: 4.4,
    numReviews: 72,
  },
  {
    name: 'Laptop Cooling Fan',
    description: 'Portable laptop cooling fan with USB power',
    price: 24.99,
    image: 'https://images.pexels.com/photos/7214/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 34,
    rating: 4.3,
    numReviews: 65,
  },
  {
    name: 'Keyboard Feet Pads',
    description: 'Replacement keyboard feet pads set',
    price: 7.99,
    image: 'https://images.pexels.com/photos/7923/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 90,
    rating: 4.0,
    numReviews: 34,
  },
  {
    name: 'Mouse Feet Replacement',
    description: 'PTFE mouse feet replacement pads',
    price: 8.99,
    image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 70,
    rating: 4.2,
    numReviews: 55,
  },
  {
    name: '27 Inch Monitor',
    description: 'QHD 27 inch display monitor',
    price: 299.99,
    image: 'https://images.pexels.com/photos/4290320/pexels-photo-4290320.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 7,
    rating: 4.8,
    numReviews: 189,
  },
  {
    name: '24 Inch Monitor',
    description: 'Full HD 24 inch display monitor',
    price: 179.99,
    image: 'https://images.pexels.com/photos/4290320/pexels-photo-4290320.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 11,
    rating: 4.7,
    numReviews: 156,
  },
  {
    name: 'Wireless Keyboard',
    description: 'Compact wireless keyboard with numeric pad',
    price: 49.99,
    image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 28,
    rating: 4.4,
    numReviews: 84,
  },
  {
    name: 'Gaming Headset',
    description: 'RGB gaming headset with surround sound',
    price: 119.99,
    image: 'https://images.pexels.com/photos/3587478/pexels-photo-3587478.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 19,
    rating: 4.6,
    numReviews: 134,
  },
  {
    name: 'USB Type-C Adapter',
    description: 'Multi-function USB-C adapter',
    price: 34.99,
    image: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 36,
    rating: 4.5,
    numReviews: 77,
  },
  {
    name: 'External Keyboard',
    description: 'Mechanical external keyboard for laptop',
    price: 69.99,
    image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 15,
    rating: 4.7,
    numReviews: 112,
  },
  {
    name: 'Laptop Bag',
    description: 'Stylish laptop bag with multiple compartments',
    price: 49.99,
    image: 'https://images.pexels.com/photos/1334597/pexels-photo-1334597.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 22,
    rating: 4.5,
    numReviews: 89,
  },
  {
    name: 'Phone Screen Cleaner',
    description: 'Microfiber cloth and screen cleaner kit',
    price: 9.99,
    image: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 65,
    rating: 4.2,
    numReviews: 52,
  },
  {
    name: 'Desk Drawer Organizer',
    description: 'Expandable desk drawer organizer',
    price: 22.99,
    image: 'https://images.pexels.com/photos/7923/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 30,
    rating: 4.3,
    numReviews: 66,
  },
  {
    name: 'USB Light',
    description: 'Flexible USB light for workspace',
    price: 14.99,
    image: 'https://images.pexels.com/photos/1038169/pexels-photo-1038169.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 44,
    rating: 4.2,
    numReviews: 59,
  },
  {
    name: 'Laptop Feet',
    description: 'Rubber laptop feet replacements',
    price: 10.99,
    image: 'https://images.pexels.com/photos/7214/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 52,
    rating: 4.1,
    numReviews: 47,
  },
  {
    name: 'Desk Pad',
    description: 'Large leather desk pad for workspace',
    price: 54.99,
    image: 'https://images.pexels.com/photos/1334597/pexels-photo-1334597.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 14,
    rating: 4.6,
    numReviews: 97,
  },
  {
    name: 'Cable Sleeves',
    description: 'Protective cable sleeves set',
    price: 15.99,
    image: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Electronics',
    countInStock: 46,
    rating: 4.4,
    numReviews: 63,
  },
];


const run = async () => {
  try {
    const connected = await connectDB();
    if (!connected) {
      console.error('Cannot seed because MongoDB is not connected.');
      process.exit(1);
    }

    // Clear all existing products to remove old ones with invalid images
    await Product.deleteMany({});
    console.log('Cleared all existing products');

    const created = await Product.insertMany(products);
    console.log(`Inserted ${created.length} sample products with valid images.`);
  } catch (err) {
    console.error('Seeding failed:', err);
  } finally {
    await mongoose.disconnect();
    process.exit(0);
  }
};

run();
